# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: computing_system_scheduler.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import messages.order_scheduler_pb2 as order__scheduler__pb2

from messages.order_scheduler_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='computing_system_scheduler.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n computing_system_scheduler.proto\x1a\x15order_scheduler.proto\"P\n\x0cSubTaskOrder\x12\x10\n\x08order_id\x18\x01 \x02(\t\x12\x1a\n\x08sub_task\x18\x02 \x02(\x0b\x32\x08.SubTask\x12\x12\n\ncluster_id\x18\x03 \x02(\x05\"3\n\x12\x43omputingSystemMsg\x12\x1d\n\x08\x63lusters\x18\x01 \x03(\x0b\x32\x0b.ClusterMsg\"/\n\nClusterMsg\x12!\n\nprocessors\x18\x01 \x03(\x0b\x32\r.ProcessorMsg\"4\n\x0cProcessorMsg\x12\r\n\x05power\x18\x01 \x02(\x05\x12\x15\n\rreserved_time\x18\x02 \x02(\x05P\x00')
  ,
  dependencies=[order__scheduler__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SUBTASKORDER = _descriptor.Descriptor(
  name='SubTaskOrder',
  full_name='SubTaskOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='SubTaskOrder.order_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub_task', full_name='SubTaskOrder.sub_task', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cluster_id', full_name='SubTaskOrder.cluster_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=139,
)


_COMPUTINGSYSTEMMSG = _descriptor.Descriptor(
  name='ComputingSystemMsg',
  full_name='ComputingSystemMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clusters', full_name='ComputingSystemMsg.clusters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=192,
)


_CLUSTERMSG = _descriptor.Descriptor(
  name='ClusterMsg',
  full_name='ClusterMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='processors', full_name='ClusterMsg.processors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=241,
)


_PROCESSORMSG = _descriptor.Descriptor(
  name='ProcessorMsg',
  full_name='ProcessorMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='power', full_name='ProcessorMsg.power', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reserved_time', full_name='ProcessorMsg.reserved_time', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=295,
)

_SUBTASKORDER.fields_by_name['sub_task'].message_type = order__scheduler__pb2._SUBTASK
_COMPUTINGSYSTEMMSG.fields_by_name['clusters'].message_type = _CLUSTERMSG
_CLUSTERMSG.fields_by_name['processors'].message_type = _PROCESSORMSG
DESCRIPTOR.message_types_by_name['SubTaskOrder'] = _SUBTASKORDER
DESCRIPTOR.message_types_by_name['ComputingSystemMsg'] = _COMPUTINGSYSTEMMSG
DESCRIPTOR.message_types_by_name['ClusterMsg'] = _CLUSTERMSG
DESCRIPTOR.message_types_by_name['ProcessorMsg'] = _PROCESSORMSG

SubTaskOrder = _reflection.GeneratedProtocolMessageType('SubTaskOrder', (_message.Message,), dict(
  DESCRIPTOR = _SUBTASKORDER,
  __module__ = 'messages.computing_system_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:SubTaskOrder)
  ))
_sym_db.RegisterMessage(SubTaskOrder)

ComputingSystemMsg = _reflection.GeneratedProtocolMessageType('ComputingSystemMsg', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTINGSYSTEMMSG,
  __module__ = 'messages.computing_system_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:ComputingSystemMsg)
  ))
_sym_db.RegisterMessage(ComputingSystemMsg)

ClusterMsg = _reflection.GeneratedProtocolMessageType('ClusterMsg', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTERMSG,
  __module__ = 'messages.computing_system_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:ClusterMsg)
  ))
_sym_db.RegisterMessage(ClusterMsg)

ProcessorMsg = _reflection.GeneratedProtocolMessageType('ProcessorMsg', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSORMSG,
  __module__ = 'messages.computing_system_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:ProcessorMsg)
  ))
_sym_db.RegisterMessage(ProcessorMsg)


# @@protoc_insertion_point(module_scope)
